[package]
name = "age"
type = "bin"
authors = [""]

[dependencies]
date = { tag = "v0.5.6", git = "https://github.com/madztheo/noir-date.git" }
age = {  tag = "main", git = "https://github.com/zkpassport/circuits", directory = "src/noir/lib/compare/age" }
utils = {  tag = "main", git = "https://github.com/zkpassport/circuits", directory = "src/noir/lib/utils" }