[package]
name = "expiry"
type = "bin"
authors = [""]

[dependencies]
date = { tag = "v0.5.6", git = "https://github.com/madztheo/noir-date.git" }
expiry = {  tag = "main", git = "https://github.com/zkpassport/circuits", directory = "src/noir/lib/data-check/expiry" }
utils = {  tag = "main", git = "https://github.com/zkpassport/circuits", directory = "src/noir/lib/utils" }